NumPy practise 1

In [3]:
import numpy as np

In [9]:
import numpy ;
print(numpy.__version__)
np.__config__.show()

2.1.2
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30154",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.11",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30154",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.27",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-f_29nkhr/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib 

c:\Users\Gitau\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


In [7]:
# null vector of size 10
n = np.zeros(10)
n

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
# memory size of any array
x = np.array([1,2,3,5,6])
size = x.size
itemsize = x.itemsize
memory_size = size*itemsize
print(memory_size)

40


In [12]:
#create a null vector of size 10 but the fifth value is 1
y = np.zeros(10)
y[4] = 1
print (y)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [4]:
# create a vector with values ranging from 10 to 49
z = np.arange(10,50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [33]:
# reversing a vector
a = np.array([89,56,90,112,76,43,10])
b = a[::-1]
b

array([ 10,  43,  76, 112,  90,  56,  89])

In [8]:
# create 3*3 matrix with values ranging from 0-8
m = np.arange(9).reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
# finding the indices of the non zero element
c = np.array([1,2,0,0,4,0])
np.where(c != 0)[0]

array([0, 1, 4])

In [38]:
# create a 3*3 identity maxtrix
h = np.identity(3, dtype=int)
h

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [43]:
# create a 3*3*3 array with random values
r = np.random.rand(3,3,3)
r

array([[[0.15538915, 0.55400239, 0.69487855],
        [0.46636255, 0.76885917, 0.79874177],
        [0.16686241, 0.94586046, 0.30986193]],

       [[0.93663692, 0.1675457 , 0.14778718],
        [0.0878403 , 0.97886863, 0.23575107],
        [0.68787837, 0.23793003, 0.33480156]],

       [[0.25436957, 0.75839415, 0.05455617],
        [0.29087638, 0.47347617, 0.80063356],
        [0.02127377, 0.81307619, 0.25388834]]])

In [58]:
#create a 10*10 array with random values and find the minimum and maximum
k = np.random.rand(10,10)
maximum =np.max(k)
minimum = np.min(k)
print(maximum)
print(minimum)

0.9916674060146338
0.050599158911938225


In [60]:
#create a random vector of size 30 and find the mean
p = np.random.rand(30)
mean = np.mean(p)
print(mean)

0.5062404718422687
