In [2]:
import numpy as np

array = np.ones((2,3))
array
array = np.pad(array, pad_width=1, mode='constant', 
               constant_values=0) 
array

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
# create a 5*5 matrix with values 1,2,3,4 just below the diagonal
j = np.zeros((5,5))
j
j= np.diag(1+np.arange(4), k = -1)
j

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [4]:
# create 8*8 matrix with a checkerboard pattern
h = np.zeros ((8,8), dtype=int)
h[1::2, ::2]= 1
h[::2, 1::2] = 1
print (h)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [17]:
#consider a (6,7,8)shape array what is the index(x,y,z)of the 100th element
x = np.unravel_index(100,(6,7,8))
print(x)

(np.int64(1), np.int64(5), np.int64(4))


In [18]:
#create a checkerboard (8,8)matrix using the tile function
u = np.array([[0,1],[1,0]])
u = np.tile(u,(4,4))
u

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [19]:
#normalize a 5*5 random matrix
k = np.random.random((5,5))
kmax = k.max()
kmin = k.min()
k = (k - kmin)/ (kmax - kmin)
k

array([[0.45850583, 0.48652997, 0.65751221, 0.99019999, 0.808091  ],
       [0.14870334, 0.84516239, 0.87076204, 0.12973688, 0.10290339],
       [0.16142254, 0.70943483, 0.7626793 , 0.22268365, 0.35799204],
       [0.05318875, 0.89799695, 0.38584518, 0.48729213, 0.33345357],
       [1.        , 0.32616315, 0.59480198, 0.4759126 , 0.        ]])

In [ ]:
#create a custom dtype that describes a colour as four unsigned bytes(RGBA)

In [20]:
#multiply a 5*3 matrix by a 3*2 matrix (real matrix product)
f= np.dot(np.ones((5,3)), np.ones((3,2)))
print (f)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [43]:
#Given a 1D array, negate all elements which are between 3 and 8
y = np.arange(1,17)
y


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [42]:
print(sum(range(5),-1))
#from numpy import *
#print(sum(range(5),-1))

10
